POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE0NjAxNzMzLCJ1c2VySWQiOjF9.Xd3Aiwcb3ppchh5wKZEnIPfD_hEyezZxT0oJHTv8ON4

{
  "name": "Test event ",
  "description": " test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}